$scope.posts = [
		{
			title:"Autumn Maple",
			image:"img/autumnmaple_bottle.png",
			url:"http://www.thebruery.com/beers/autumnmaple.html",
			blurb:"A delicious beer with a heavy dose of malt.  Even tastier in it's imperial release.",
			category:"Beer",
		},
		{
			title:"Hop Drop n' Roll",
			image:"img/HopDrop.png",
			url:"http://nodabrewing.com/beer/hop-drop-n-roll/",
			blurb:"This beer had a great bouquet of hops.  Lost of aroma and a great crisp clean taste.",
			category:"Beer",
		},
		{
			title:"Rugbrod",
			image:"img/rugbrod_bottle.png",
			url:"http://www.thebruery.com/beers/rugbrod.html",
			blurb:"Great rye bite in this beer and yet very drinkable.",
			category:"Beer",
		},
		{
			title:"Double Actuator",
			image:"img/double_actuator_hero.png",
			url:"http://bottlelogic.com/beers/",
			blurb:"Heavy hop profile in this beer. If DIPA's are your thing definitely give this one a try.",
			category:"Beer",
		},
		{
			title:"Focal Banger",
			image:"img/fbang.png",
			url:"http://alchemistbeer.com/",
			blurb:"Pretty tasty DIPA from the people who brought you Heady Topper.",
			category:"Beer",
		},
		{
			title:"The Big Lebowski",
			image:"img/big-lebowski-dude.jpg",
			url:"http://www.imdb.com/title/tt0118715/?ref_=fn_al_tt_1",
			blurb:"The Dude abides...",
			category:"Movies",
		},
		{
			title:"Star Wars",
			image:"img/star-wars-yoda-may-the-force.jpg",
			url:"http://www.imdb.com/title/tt0076759/?ref_=nv_sr_2",
			blurb:"May the force be with you.",
			category:"Movies",
		},
		{
			title:"The Good, The Bad, and The Ugly",
			image:"img/good-bad-and-ugly.jpg",
			url:"http://www.imdb.com/title/tt0060196/?ref_=fn_al_tt_1",
			blurb:"You catch yourself whistling the tune from this movie on a hot day int he desert.",
			category:"Movies",
		},
		{
			title:"Fight Club",
			image:"img/fight-club-rules.jpg",
			url:"http://www.imdb.com/title/tt0137523/?ref_=nv_sr_1",
			blurb:"Don't talk about this post.",
			category:"Movies",
		},
		{
			title:"LA Galaxy",
			image:"img/LA_Galaxy.jpg",
			url:"http://www.lagalaxy.com/schedule",
			blurb:"LA, clap, clap, clap, GALAXY!",
			category:"Sports",
		},
		{
			title:"Tottenham Hotspur",
			image:"img/tottenham-logo.jpg",
			url:"http://www.tottenhamhotspur.com/",
			blurb:"Would love to watch a game in London someday.",
			category:"Sports",
		},
		{
			title:"EC Simmons",
			image:"img/ecimmons.jpg",
			url:"http://www.ecsurfboards.com/surfboards/neo-classics/ecimmons/",
			blurb:"This board goes fast!",
			category:"Surfboards",
		},
		{
			title:"EC Does It",
			image:"img/ecdoesit.jpg",
			url:"http://www.ecsurfboards.com/surfboards/neo-classics/ecdoesit/",
			blurb:"Barrel Hunter",
			category:"Surfboards",
		},
		{
			title:"Gospel Whiskey Runners",
			image:"img/gospelwhiskey.jpg",
			url:"http://www.gospelwhiskeyrunners.com/",
			blurb:"Good tunes.",
			category:"Music",
		},
		{
			title:"Gregory Alan Isakov",
			image:"img/gregory.jpg",
			url:"http://gregoryalanisakov.com/",
			blurb:"Good tunes.",
			category:"Music",
		}
	] 